// Code generated by MockGen. DO NOT EDIT.
// Source: isula.org/isula-transform/transform (interfaces: StorageDriver)

// Package docker is a generated GoMock package.
package docker

import (
	gomock "github.com/golang/mock/gomock"
	types "isula.org/isula-transform/types"
	reflect "reflect"
)

// MockStorageDriver is a mock of StorageDriver interface
type MockStorageDriver struct {
	ctrl     *gomock.Controller
	recorder *MockStorageDriverMockRecorder
}

// MockStorageDriverMockRecorder is the mock recorder for MockStorageDriver
type MockStorageDriverMockRecorder struct {
	mock *MockStorageDriver
}

// NewMockStorageDriver creates a new mock instance
func NewMockStorageDriver(ctrl *gomock.Controller) *MockStorageDriver {
	mock := &MockStorageDriver{ctrl: ctrl}
	mock.recorder = &MockStorageDriverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorageDriver) EXPECT() *MockStorageDriverMockRecorder {
	return m.recorder
}

// Cleanup mocks base method
func (m *MockStorageDriver) Cleanup(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup", arg0)
}

// Cleanup indicates an expected call of Cleanup
func (mr *MockStorageDriverMockRecorder) Cleanup(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockStorageDriver)(nil).Cleanup), arg0)
}

// GenerateRootFs mocks base method
func (m *MockStorageDriver) GenerateRootFs(arg0, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRootFs", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRootFs indicates an expected call of GenerateRootFs
func (mr *MockStorageDriverMockRecorder) GenerateRootFs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRootFs", reflect.TypeOf((*MockStorageDriver)(nil).GenerateRootFs), arg0, arg1)
}

// TransformRWLayer mocks base method
func (m *MockStorageDriver) TransformRWLayer(arg0 *types.IsuladV2Config, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransformRWLayer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransformRWLayer indicates an expected call of TransformRWLayer
func (mr *MockStorageDriverMockRecorder) TransformRWLayer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransformRWLayer", reflect.TypeOf((*MockStorageDriver)(nil).TransformRWLayer), arg0, arg1)
}
